name: .NET build & test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  COVERAGE_WARNING_THRESHOLD: 99
  COVERAGE_THRESHOLD: 20
  MUTATION_THRESHOLD: 2

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        task: [Task1, Task2, Task3, Task4, Task8]
      fail-fast: false
    defaults:
      run:
        working-directory: ./${{ matrix.task }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 8.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore -warnaserror /p:RunAnalyzers=true

      - name: Code style check
        run: dotnet format --verify-no-changes

      - name: Test
        run: dotnet test --no-build --verbosity normal --logger trx --collect:"XPlat Code Coverage"

      - name: Combine Coverage Reports
        uses: danielpalme/ReportGenerator-GitHub-Action@5.4.13
        with:
          reports: "**/coverage.cobertura.xml"
          targetdir: "${{ matrix.task }}/coverage"
          reporttypes: "Cobertura"
          verbosity: "Info"
          title: "${{ matrix.task }} Code Coverage"
          tag: "${{ github.run_number }}_${{ github.run_id }}"
          toolpath: "reportgeneratortool"

      - name: Create Code Coverage Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: "${{ matrix.task }}/coverage/Cobertura.xml"
          badge: true
          fail_below_min: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: false
          indicators: true
          output: both
          thresholds: "${{ env.COVERAGE_THRESHOLD }} ${{ env.COVERAGE_WARNING_THRESHOLD }}"
      - name: Add Coverage PR Comment
        if: github.event_name == 'pull_request' && github.event.pull_request.user.login != 'dependabot[bot]'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          recreate: true
          path: code-coverage-results.md
      - name: Install dotnet-stryker globally
        run: dotnet tool install -g dotnet-stryker
      - name: Run mutation test
        run: dotnet stryker --mutation-level Complete --break-at ${{ env.MUTATION_THRESHOLD }}
