name: .NET build & test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  COVERAGE_WARNING_THRESHOLD: 99
  COVERAGE_THRESHOLD: 20
  MUTATION_THRESHOLD: 2

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        task: [Task1, Task2, Task3, Task9]
      fail-fast: false
    defaults:
      run:
        working-directory: ./${{ matrix.task }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 8.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore -warnaserror /p:RunAnalyzers=true

      - name: Code style check
        run: dotnet format --verify-no-changes

      - name: Test
        run: dotnet test --no-build --verbosity normal --logger trx --collect:"XPlat Code Coverage"

      - name: Install dotnet-stryker globally
        run: dotnet tool install -g dotnet-stryker
      - name: Run mutation test
        run: dotnet stryker --mutation-level Complete --break-at ${{ env.MUTATION_THRESHOLD }}
